### ISSUE TITLE
[request] TFJS model availability

### ISSUE THREAD

**Issue by edwinRNDR** [sdll/psenet#1]
Hi there, I read on your blog that you have made a tfjs version of PSEnet. I found both this repo and your PR to the tensorflow-js repo. In the code I found a link to the model (https://storage.googleapis.com/gsoc-tfjs/models/text-detection/quantized/1/psenet/model.json) but that appears to be down. Is there any way to get my hands on those files?

**Comment by aptlin** [comment]
Hi! You can now find the converted weights on [Dropbox](https://www.dropbox.com/sh/asa5cjkwk1gnhij/AADw_59T58VM1-fzWlviWLDma?dl=0)
